Fixed facet filters disappear and won’t come back after filter reset
PrestaShop/ps_facetedsearch pull request #293
Opened 2020-12-18 13:11 UTC by sowebdev

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Before fix, facet filters could disappear on filtering and not come back on reset.
| Type?         | bug fix
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes PrestaShop/Prestashop#22488.
| How to test?  | See ticket.

2020-12-18 13:42 UTC, NeOMakinG requested changes
Hello @sowebdev , thanks for your contribution !

You changed the structure without changing the indentation, please update it :)

2020-12-18 14:45 UTC, sowebdev commented
@NeOMakinG Sorry, I hope it's ok now :)

2020-12-18 15:19 UTC, NeOMakinG approved these changes

2020-12-21 09:07 UTC, PierreRambaud approved these changes

2020-12-21 09:08 UTC, PierreRambaud commented
Don't care about CS fixer, I will fix it in another Pull request

2021-01-12 17:37 UTC, khouloudbelguith commented
Hi @sowebdev,

I have an issue following these steps:
1. Go to the back office and create a new feature and one new feature value
2. Create a new product with add the last feature & value to this product
3. configure the ps_facetedsearch to enable this feature
4. Disable the price filter
5. Go to FO > home page
6. Filter by the new Feature
7. See the error
![image](https://user-images.githubusercontent.com/16067358/104350880-f6932280-5504-11eb-8124-10326702c1ed.png)

I tried with a new category that has only one product
![image](https://user-images.githubusercontent.com/16067358/104351016-1f1b1c80-5505-11eb-8e9a-37f1f19ba2df.png)

Thank you!

2021-02-11 07:34 UTC, sarahdib commented
Hello

Since we had no news from you for more than 30 days, I'll close this pull request. Feel free to re-open this pull request if you can provide more details.

Thank you!

2021-02-11 07:34 UTC, closed without merging