Update Github Actions
PrestaShop/ps_facetedsearch pull request #584
Opened 2022-01-05 08:49 UTC by jf-viguier

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Please be specific when describing the PR. <br> Every detail helps: versions, browser/server configuration, specific module/theme, etc. Feel free to add more information below this table.
| Type?         | bug fix / improvement / new feature / refacto / critical
| BC breaks?    | yes / no
| Deprecations? | yes / no
| Fixed ticket? | Fixes PrestaShop/Prestashop#{issue number here}.
| How to test?  | Please indicate how to best verify that this PR is correct.

2022-01-05 08:51 UTC, PierreRambaud requested changes
Thanks for your contribution, but could you please properly fill the description table?

2022-01-05 10:39 UTC, jf-viguier commented
@PierreRambaud what more do you want ? I've followed @Progi1984 guidelines

2022-01-06 08:48 UTC, PierreRambaud approved these changes

2022-01-06 08:48 UTC, merged

2022-01-06 08:48 UTC, PierreRambaud commented
Thank you @jf-viguier