Check access to product on category listing
PrestaShop/ps_facetedsearch pull request #612
Opened 2022-02-07 10:31 UTC by bibips

Products that were not accessible by the user were still visible on the listing

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Verifies that the user has the right to access the product
| Type?         | bug fix 
| BC breaks?    |  no
| Deprecations? | no
| Fixed ticket? | Fixes PrestaShop/Prestashop#27601.
| How to test?  | **On Administration**<br/>1. On category " Clothes", go to sub-category "Men" and remove access to all groups<br/>2. Create a product "test" with only the category "Men"<br/>**On store**<br/>1. Go to the category "Clothes"<br/>2. Sub-category "Men" isn't display and you can't see the produt "test"

2022-02-07 10:53 UTC, PierreRambaud requested changes
Thanks for your contribution, but I think you didn't test it at all, as the Group class doesn't exist in this scope, same for FrontController

2022-02-08 17:04 UTC, PierreRambaud submitted a review, later dismissed

2022-02-09 10:03 UTC, bibips commented
@PierreRambaud Thanks for your review

2022-02-09 13:34 UTC, PierreRambaud commented
> @PierreRambaud Thanks for your review

Let's wait for other maintainer to review this PR and put it in QA :)

2022-02-09 13:46 UTC, kpodemski requested changes
Could you add the test based on the group that doesn't have access to the specific category? IMHO right now, you're testing a scenario that is always true.

2022-02-23 23:14 UTC, bibips commented
@kpodemski I just added a commit with more tests

2022-02-28 07:22 UTC, PierreRambaud approved these changes

2022-03-01 07:56 UTC, Progi1984 approved these changes

2022-03-11 11:12 UTC, florine2623 approved these changes
Hello @bibips ,

Thanks for the PR !

Initial case is looking good to me.

https://user-images.githubusercontent.com/16019289/157853401-b33b43fb-8ca1-416d-9026-5f5a0bb2c009.mov

Tested on existing customer groups, newly created customer groups.
Tested on Disabled/Deleted Customer groups.
Checked case when Category is disabled/deleted.
Checked product in FO when product is in multiple categories.

It is QA ✅ 
Thanks!

2022-03-11 12:06 UTC, merged

2022-03-11 12:06 UTC, Progi1984 commented
Thanks @florine2623  & @bibips