Allows filtering products on manufacturer pages
PrestaShop/ps_facetedsearch pull request #615
Opened 2022-02-13 00:11 UTC by titodevera

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Allows filtering products on manufacturer pages.<br>Tested on PrestaShop 1.7.8.3, "classic" theme, PHP 7.4
| Type?         | new feature
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | -
| How to test?  | Set two columns layout for brands and clear the filters cache, the filters should appears on the manufacturers pages now.

2022-02-14 08:24 UTC, matthieu-rolland reviewed
thank you for your contribution @titodevera !

For adding new features, we have a small process:

1/ Create a feature request ([click here](https://github.com/PrestaShop/PrestaShop/issues/new?assignees=&labels=Feature&template=2_feature_request.yml)) and link your pull request into it

2/ Product team will validate your feature request before your PR can be accepted 👍

2022-02-19 22:03 UTC, matks commented
Looks like this PR is now linked to feature https://github.com/PrestaShop/PrestaShop/issues/15137 👍

2022-02-28 17:06 UTC, matks requested changes
Dear @titodevera sorry for late answer. CI reports some issues
- phpstan reports variables that might sometimes not be defined
- php-cs-fixer reports codestyle issues

Can you please fix it?

2022-03-21 17:34 UTC, Hlavtox commented
Hello @titodevera, I think you didn't test your PR, because there is no way this works. You are selecting products from home category.

I have a PR work in progress here - https://github.com/PrestaShop/ps_facetedsearch/pull/531, everything is ready, except fetching the correct products in the SQL query, maybe you can fork it and try it.

2022-04-04 15:25 UTC, matks commented
@Hlavtox thanks for the help

In the meantime I close this PR as stale 😢

2022-04-04 15:25 UTC, closed without merging