Fixed Price And URL When Filtering With Combinations
PrestaShop/ps_facetedsearch pull request #718
Opened 2022-09-28 21:59 UTC by TheKruspe

- Added `id_product_attribute` To Select-Fields

Edit: I just noticed the product default combination gets ignored if a filter based on attribute groups is active.

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | When filtering products with combinations, only the default combination was used to determine price and url of the results.
| Type?         | bug fix / improvement
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes PrestaShop/Prestashop#15738 and PrestaShop/Prestashop#15164
| How to test?  | Filter for products with multiple combinations and different prices. Click on a product to navigate to the correct combination.

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/ps_facetedsearch/718)

2022-09-29 20:03 UTC, matks requested changes
Hi @TheKruspe the CI is red can you check why tests are failing?

2022-10-01 20:22 UTC, TheKruspe commented
I just made changes that restore the default combination behaviour when using attribute filters (mentioned in edit). 

Furthermore, it is now possible to display every combination of a product as a separate product. I'm not sure if I should leave this feature in this branch. I will now check why tests are failing.

2022-10-03 16:16 UTC, TheKruspe commented
Some tests need to be updated, because I modified `useFiltersAsInitialPopulation` . I'll fix and update later this week.

2023-05-26 06:59 UTC, kpodemski commented
@Hlavtox have you seen this PR? shall we take over it?

2023-05-26 17:23 UTC, TheKruspe commented
@kpodemski I unfortunately wasn't able to find the time. If you have any questions, let me know.

2023-08-01 11:11 UTC, Hlavtox commented
@TheKruspe Implemented in develop branch. :-)

2023-08-01 11:11 UTC, closed without merging