Unify availability naming
PrestaShop/ps_facetedsearch pull request #780
Opened 2023-01-31 17:04 UTC by Hlavtox

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | I have unified the naming of quantity/availability.
| Type?         | refacto
| BC breaks?    | No BC breaks, FO template was already using 'availability' naming.
| Deprecations? | no
| Fixed ticket? | 
| How to test?  | See that availability filter works correctly.

2023-02-09 10:13 UTC, kpodemski commented on upgrade/upgrade-3.11.0.php
> +    Db::getInstance()->execute(
3.11 is now live, it should be part of 3.12

2023-02-09 10:13 UTC, kpodemski requested changes
The upgrade file probably requires 3.12.

2023-02-09 15:05 UTC, Hlavtox commented
@kpodemski Done, but let's wait after 3.11.1 release

2023-02-16 13:30 UTC, kpodemski submitted a review, later dismissed

2023-02-21 15:36 UTC, kpodemski approved these changes

2023-02-21 15:42 UTC, AureRita commented
Hi @Hlavtox 

Thank you for your PR! I tested it and we have the good bump version and we still have the avaibility section as you can see see : 
![image](https://user-images.githubusercontent.com/100699445/220390635-a784b935-d93b-47ab-8f4d-3d4c37263157.png)

Thank you !

2023-02-21 15:43 UTC, merged