Update GH workflows: Node 14-16, PHP 7.2-8.2, Github actions v3
PrestaShop/ps_facetedsearch pull request #902
Opened 2023-08-15 03:37 UTC by leemyongpakvn

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Recent PSs' test has a lot of warnings about outdated Node, GH actions <br> (9 JS warnings and 21 PHP warnings): <br> https://github.com/PrestaShop/ps_facetedsearch/actions/runs/5793944220 <br> https://github.com/PrestaShop/ps_facetedsearch/actions/runs/5793944222
| Type?         | improvement
| BC breaks?    | no
| Deprecations? | yes
| Fixed ticket? | Fixes PrestaShop/Prestashop#{issue number here}.
| How to test?  | GH workflows complete with less warnings about outdated Node, PHP, actions.

2023-08-15 04:00 UTC, leemyongpakvn commented
@Hlavtox Feel free to bump minimum compatibility to PHP 7.1.3 and PS 1.7.7, module version to 4.0.0 as we agreed at [issues/32841](https://github.com/PrestaShop/PrestaShop/issues/32841) when you think it's the right time.

2023-08-16 15:40 UTC, matthieu-rolland submitted a review, later dismissed

2023-08-16 16:52 UTC, LouisAUTHIE submitted a review, later dismissed

2023-08-22 09:26 UTC, kpodemski requested changes
Hi @leemyongpakvn 

In order for CI to be helpful for this module, let's consider this scenario:
- from now on we would check only for PHP 7.2 to 8.2 compatibility whereas the module is still compatible with PrestaShop 1.7.6 which should work with as low as PHP 5.6. Even PrestaShop 1.7.7 supports PHP 7.1+, so either we should have tests for PHP 7.1+, or we should bump the compatibility to PrestaShop 8.

2023-08-22 09:38 UTC, leemyongpakvn commented
@kpodemski As we can see in _Files changed_, this repo lacks of PHP 7.1 check for a long time, not after this PR. I suggested **matks** add it himself in Slack but he forgot or has no time to do ;) Added by the way.

2023-08-22 09:46 UTC, kpodemski approved these changes

2023-08-22 09:46 UTC, merged

2023-08-22 09:47 UTC, kpodemski commented
thanks @leemyongpakvn 

the next step it to drop support for 1.7.6