Release 3.13.2
PrestaShop/ps_facetedsearch pull request #921
Opened 2023-09-15 11:09 UTC by Hlavtox

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Release 3.13.2
| Type?         | 
| BC breaks?    |
| Deprecations? |
| Fixed ticket? | 
| How to test?  | As the PR only contains two simple PRs that have been properly tested (https://github.com/PrestaShop/ps_facetedsearch/pull/916 and https://github.com/PrestaShop/ps_facetedsearch/pull/895), I think that tests green are sufficient.

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/PrestaShop/ps_facetedsearch/921)

2023-09-15 12:08 UTC, nicosomb requested changes
You forgot `ps_facetedsearch.php`changes 😉

2023-09-15 13:52 UTC, Hlavtox commented
@nicosomb I am stuuuuuupid. :-)

2023-09-15 13:58 UTC, nicosomb approved these changes

2023-09-15 14:19 UTC, boherm approved these changes

2023-09-18 10:06 UTC, boherm approved these changes

2023-09-18 14:37 UTC, MhiriFaten approved these changes
Hello @Hlavtox ,

I have checked this release and LGTM.

It is QA approved ✔️

2023-09-18 14:40 UTC, merged